server:
  port: 7081

eureka:
  instance:
    hostname: 192.168.3.7
    instance-id: eureka.server.com:7081
  client:
    #registerWithEureka: false
    #fetchRegistry: false  搭建eureka集群的时候，注释掉这2行代码
    serviceUrl:
      defaultZone: http://192.168.3.7:8081/eureka/
  server:
    enable-self-preservation: false #关闭自我保护机制
    eviction-interval-timer-in-ms: 4000 #设置清理间隔（单位：毫秒，默认是60 * 1000）
